FROM jenkins/jenkins:lts

USER root

# Install Git, Podman, curl, and other tools
RUN apt-get update && \
    apt-get install -y git podman curl && \
    rm -rf /var/lib/apt/lists/*

# Install kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    chmod +x kubectl && mv kubectl /usr/local/bin/

USER jenkins